name: Push on develop

on:
  schedule:
    - cron: 46 6 * * *
  push:
    branches:
      - develop

jobs:
  build:
    name: Build
    strategy:
      fail-fast: false
      matrix:
        os:
          - "ubuntu-latest"
          - "macos-latest"
          - "windows-latest"
    runs-on: ${{ matrix.os }}
    env:
      OPAMSOLVERTIMEOUT: 3600
      OPAMVERBOSE: 1
    steps:

      - name: Add msbuild to PATH (windows)
        uses: microsoft/setup-msbuild@v1.1
        if: runner.os == 'Windows'

      - uses: actions/setup-python@v2
        if: runner.os != 'Linux'

      - name: install md5sum (macOS)
        run: brew install md5sha1sum gnu-sed --with-default-names
        if: runner.os == 'macOS'

      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: develop
          fetch-depth: 1
          path: develop
          submodules: true

      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: main
          fetch-depth: 1
          path: main

      - name: Determine the default OPAM Repo
        id: determine-default-opam-repo
        # See https://docs.github.com/en/actions/reference/context-and-expression-syntax-for-github-actions#runner-context
        # and https://github.com/ocaml/setup-ocaml/blob/4ac56b0fd440c3eef30fd1e34c96e0c740a807da/src/constants.ts#L45
        shell: bash
        run: |
          if [ "${{ runner.os }}" = "Windows" ] ; then
            DEFAULT_OPAM_REPO="https://github.com/fdopen/opam-repository-mingw.git#opam2"
          else
            DEFAULT_OPAM_REPO="https://github.com/ocaml/opam-repository.git"
          fi
          echo "::set-output name=opam-repo-default::$(echo "$DEFAULT_OPAM_REPO")"

      - name: Setup OCaml
        uses: ocaml/setup-ocaml@v2
        with:
          ocaml-compiler: "4.12.1"
          opam-repositories: |
            satysfi-external: https://github.com/gfngfn/satysfi-external-repo.git
            satyrographos-repo: https://github.com/na4zagin3/satyrographos-repo.git
            default: ${{ steps.determine-default-opam-repo.outputs.opam-repo-default }}

      - name: Run script
        shell: bash
        run: |
          cd "${{ github.workspace }}/develop"
          ./update.sh "${{ runner.os }}" "${{ runner.arch }}" "${{ runner.temp }}" "${{ github.workspace }}/main/packages" "${{ github.workspace }}/main/store/archives" "${{ github.workspace }}/main/build-log/failed-packages"
        env:
          OPAMLOGS: "${{ github.workspace }}/main/build-log"

      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: main
          fetch-depth: 1
          path: main-new

      - name: Copy files
        shell: bash
        run: |
          cd "${{ github.workspace }}/main"
          [ -e store ] && cp -R -n store "${{ github.workspace }}/main-new/" || true
          [ -e packages ] && cp -R -n packages "${{ github.workspace }}/main-new/" || true
          [ -e build-log ] && cp -R -n build-log "${{ github.workspace }}/main-new/" || true

      - name: Add files
        shell: bash
        run: |
          cd "${{ github.workspace }}/main-new"
          if [ ! -f repo ]; then
            echo "opam-version: \"2.0\"" > repo
            echo "upstream: \"https://github.com/yasuo-ozu/satyrographos-repo-bin\"" >> repo
            git add repo
          fi
          [ -f store ] && git add -f store || true
          [ -f packages ] && git add -f packages || true
          [ -f build-log ] && git add -f build-log || true

      - name: Commit & Push changes
        uses: actions-js/push@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN  }}
          directory: "main-new"


