name: Install test

on:
  push:
    branches:
      - main

jobs:
  install:
    name: Install Test
    strategy:
      fail-fast: false
      matrix:
        os:
          - "ubuntu-latest"
          - "macos-latest"
          - "windows-latest"
    runs-on: ${{ matrix.os }}
    env:
      OPAMSOLVERTIMEOUT: 3600
      OPAMVERBOSE: 1
    steps:

      - name: Add msbuild to PATH (windows)
        uses: microsoft/setup-msbuild@v1.1
        if: runner.os == 'Windows'
      - name: install crew packs (macOS)
        run: brew install md5sha1sum gnu-sed
        if: runner.os == 'macOS'
      - name: Determine the default OPAM Repo
        id: determine-default-opam-repo
        # See https://docs.github.com/en/actions/reference/context-and-expression-syntax-for-github-actions#runner-context
        # and https://github.com/ocaml/setup-ocaml/blob/4ac56b0fd440c3eef30fd1e34c96e0c740a807da/src/constants.ts#L45
        shell: bash
        run: |
          if [ "${{ runner.os }}" = "Windows" ] ; then
            DEFAULT_OPAM_REPO="https://github.com/fdopen/opam-repository-mingw.git#opam2"
          else
            DEFAULT_OPAM_REPO="https://github.com/ocaml/opam-repository.git"
          fi
          echo "::set-output name=opam-repo-default::$(echo "$DEFAULT_OPAM_REPO")"

      - name: Setup OCaml
        uses: ocaml/setup-ocaml@v2
        with:
          ocaml-compiler: "4.12.1"
          opam-repositories: |
            satyrographos-repo-bin: https://github.com/yasuo-ozu/satyrographos-repo-bin.git
            default: ${{ steps.determine-default-opam-repo.outputs.opam-repo-default }}

      - name: Install
        shell: bash
        run: |
          if where gsed &>/dev/null ; then
            alias sed=gsed
          fi
          if where opam.cmd &>/dev/null ; then
            alias opam="$(where opam.cmd)"
          elif where opam.exe &>/dev/null ; then
            alias opam="$(where opam.exe)"
          fi
          opam list --columns=package --installable --color=never --or -A -V satysfi satyrpgraphos | sed -e '/^#/d' | while read PKG; do
            opam install -y "$PKG"
            opam remove -a -y "$PKG"
          done
